# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dyndns < Formula
  desc "Dynamic DNS configurator for namecheap.com"
  homepage "https://github.com/gertd/dyndns"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gertd/dyndns/releases/download/v0.0.1/dyndns-0.0.1-darwin-arm64.zip"
      sha256 "5a7399ed0b92a9e066928902b26317521890a9d818b42b90d28fb4fb1c068477"

      def install
        bin.install "dyndns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/dyndns/releases/download/v0.0.1/dyndns-0.0.1-darwin-amd64.zip"
      sha256 "752ec865824a52cf6841b3bec937ad7c573225a8065cf72ffd9ca0616d9c365c"

      def install
        bin.install "dyndns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/dyndns/releases/download/v0.0.1/dyndns-0.0.1-linux-arm64.zip"
      sha256 "c861827464ff23159115e6772c122608e0c88251eafc564f4ae5b4c5dd083e72"

      def install
        bin.install "dyndns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/dyndns/releases/download/v0.0.1/dyndns-0.0.1-linux-amd64.zip"
      sha256 "5e94c95d13d2a389b0b0e02a54d987065687dbb4eb5e10cfa4ca7973861238af"

      def install
        bin.install "dyndns"
      end
    end
  end

  test do
    system "#{bin}/dyndns version"
  end
end
