# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topaz < Formula
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.33.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.33.6/topaz_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "b5183dfe49acc989c6ea7df2d79374f7e67ce45b848f1e2ebc232ae62397b870"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.33.6/topaz_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "8e7a1d7da1bb99f0d7f38e1ce31e2887b653cc5c3db34e1399bc763aaeb1f611"

      def install
        bin.install "topaz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.33.6/topaz_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "14f92dff4af21e6c15b4e764f9b25bf1b248465bd0c014c7a53c4116d5894f89"
      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.33.6/topaz_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "3e4b38a023bc98bb9366fa3220d9d3696be2eec769ac3e8a604d71633e09d130"
      def install
        bin.install "topaz"
      end
    end
  end

  test do
    system "#{bin}/topaz version"
  end
end
