# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volbo < Formula
  desc "Volbo CLI"
  homepage "https://github.com/gertd/volbo"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gertd/volbo/releases/download/v0.0.5/volbo-0.0.5-darwin-arm64.zip"
      sha256 "5ff9b31bc6f7b822773edd1d2822f1f4c667aada5edef767c72f730be341767a"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.5/volbo-0.0.5-darwin-amd64.zip"
      sha256 "fcbb4c231f626169a460dd1991d7e918717eea772db5308e38a32f2cf953b844"

      def install
        bin.install "volbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/volbo/releases/download/v0.0.5/volbo-0.0.5-linux-arm64.zip"
      sha256 "64be37d842d00b18c7137b97ad7cb53fb3687f32a8af50c46d85068ba77b3f4c"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.5/volbo-0.0.5-linux-amd64.zip"
      sha256 "047214bf72f5309b64472fb562f36baf457bd1a7e6667d61f009529ab5ef484c"

      def install
        bin.install "volbo"
      end
    end
  end

  test do
    system "#{bin}/volbo version"
  end
end
