# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volbo < Formula
  desc "Volbo CLI"
  homepage "https://github.com/gertd/volbo"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gertd/volbo/releases/download/v0.0.3/volbo-0.0.3-darwin-arm64.zip"
      sha256 "2940484f5d96592b2acce9f5236f4f516f991e27c2dc16d789ee1f64bea4ddd1"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.3/volbo-0.0.3-darwin-amd64.zip"
      sha256 "f030135455bccdcd62276cd3b88c682f3038da520b6e0e2df719c7bac27e24b1"

      def install
        bin.install "volbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/volbo/releases/download/v0.0.3/volbo-0.0.3-linux-arm64.zip"
      sha256 "3c78413ac8c09391fa0342f97ab072fd4e54e66d791901b111836b7ae6fa0af1"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.3/volbo-0.0.3-linux-amd64.zip"
      sha256 "6e1aa938226dee17d2ecf79ddd43a5b054d25f78825cba799e6ee9a7a2281681"

      def install
        bin.install "volbo"
      end
    end
  end

  test do
    system "#{bin}/volbo version"
  end
end
