# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Volbo < Formula
  desc "Volbo CLI"
  homepage "https://github.com/gertd/volbo"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gertd/volbo/releases/download/v0.0.4/volbo-0.0.4-darwin-arm64.zip"
      sha256 "80854c76e4249a2f5729e6ac18e23771094cc8a37508947b4b65cb1ce7939d48"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.4/volbo-0.0.4-darwin-amd64.zip"
      sha256 "e27ced4f7d6a368cf468f79c2ea3f8dbe3d6d458f4067efaeafaf2d4d371b14d"

      def install
        bin.install "volbo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/volbo/releases/download/v0.0.4/volbo-0.0.4-linux-arm64.zip"
      sha256 "df50fe6bd2b194a222e3ed7be873165bc39aa58089b6288dc35c45f170ee924b"

      def install
        bin.install "volbo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gertd/volbo/releases/download/v0.0.4/volbo-0.0.4-linux-amd64.zip"
      sha256 "41fc495d330ec7749252787b8d4dd42f11113f7fbdd920bdfba71b4f166b14c8"

      def install
        bin.install "volbo"
      end
    end
  end

  test do
    system "#{bin}/volbo version"
  end
end
