# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YamlReaderHomebrew < Formula
  desc "yaml file reader"
  homepage "https://github.com/gertd/yaml-reader"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.9/yaml-reader", using: CurlDownloadStrategy
      sha256 "b63d9d37b9d3e6cdde01663a03da96f957ad2c4f09182a19502d1226a3feca7e"

      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.9/yaml-reader", using: CurlDownloadStrategy
      sha256 "2629e6d7b28e963ccba2108db2c49a0b471ed00311d96a66594899011691c54e"

      def install
        bin.install "yaml-reader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.9/yaml-reader", using: CurlDownloadStrategy
      sha256 "e3c8977ebdc6acd4533820b2f46f9004f414d0650b34fe960983a2f7f37ec427"
      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.9/yaml-reader", using: CurlDownloadStrategy
      sha256 "b003e663a5e45aac9dce7e6956b33263f06d26be2c6ee63ed12e5dd251b40852"
      def install
        bin.install "yaml-reader"
      end
    end
  end

  test do
    system "#{bin}/yaml-reader version"
  end
end
