# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YamlReader < Formula
  desc "yaml file reader"
  homepage "https://github.com/gertd/yaml-reader"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.10/yaml-reader", using: CurlDownloadStrategy
      sha256 "e0f143db9de65a6bb1125c1d001d5df2c79ac6d29eb5b18d246202c0d798405e"

      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.10/yaml-reader", using: CurlDownloadStrategy
      sha256 "16e64fe319072e42c09134e20a32cbc87031396c3472c5e5bc113cd4389c3336"

      def install
        bin.install "yaml-reader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.10/yaml-reader", using: CurlDownloadStrategy
      sha256 "8bbeffc07f8e2a5b69c8d5592dbbf8940076589cc732024b55f94a7a0e92c179"
      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.10/yaml-reader", using: CurlDownloadStrategy
      sha256 "cbd940020df732f2fccae486b8c1e4da5b0ff5e6ce2290858d47ab4459853131"
      def install
        bin.install "yaml-reader"
      end
    end
  end

  test do
    system "#{bin}/yaml-reader version"
  end
end
