# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YamlReaderHomebrew < Formula
  desc "yaml file reader"
  homepage "https://github.com/gertd/yaml-reader"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.8/yaml-reader_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "d08ee2ca55a1cc666f7faa490a7c2b4d5d08c63b490c2e8199f5d230b8de0092"

      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.8/yaml-reader_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "357c0d2f0b071c4608ddaa00f2fe1b1f04c1cf901a747ba02351ff35160f4de1"

      def install
        bin.install "yaml-reader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.8/yaml-reader_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "a4425e257ead5fcff92a256e3f9e08b169ea7cba964029dd96d6528ed9b37222"
      def install
        bin.install "yaml-reader"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gertd/yaml-reader/releases/download/v1.0.8/yaml-reader_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "c0c509d1813996b2fbb6a14607cc87052d6f400eb62b22f63e00bb9f5d3b7da4"
      def install
        bin.install "yaml-reader"
      end
    end
  end

  test do
    system "#{bin}/yaml-reader version"
  end
end
